---
project: reusableapp
default-region: eu-west-1
code-bucket: gordon-reusableapp-0do1mc7
apps:
  - helloworld:
      settings:
        b: global_value

#
# lambda-settings:
#     d: value_d


# lambdas:
#   hellopyroot:
#     code: helloworld/hellopy.py
#     settings:
#         a: b
