lambdas:

  rule:
    code: rule
    handler: rule.handler
    runtime: python
    description: Manages Cloudwatch event rules
    timeout: 300
    policies:
      manage_rules:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "events:DescribeRule"
              - "events:PutRule"
              - "events:DeleteRule"
            Resource: "arn:aws:events:*:*:*"
            Effect: "Allow"

  target:
    code: target
    handler: target.handler
    runtime: python
    description: Manages Cloudwatch event targets
    timeout: 300

    policies:
      manage_rules:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "events:PutTargets"
              - "events:RemoveTargets"
              - "events:ListTargetsByRule"
            Resource: "arn:aws:events:*:*:*"
            Effect: "Allow"
