lambdas:

  version:
    code: version.py
    description: Publishes new versions of Lambdas.
    timeout: 300
    policies:
      read_kinesis:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "lambda:PublishVersion"
              - "lambda:GetFunction"
            Resource: "arn:aws:lambda:*:*:*"
            Effect: "Allow"

  alias:
    code: alias.py
    description: Manages aliases of Lambdas.
    timeout: 300
    policies:
      read_kinesis:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "lambda:CreateAlias"
              - "lambda:DeleteAlias"
              - "lambda:GetAlias"
              - "lambda:UpdateAlias"
            Resource: "arn:aws:lambda:*:*:*"
            Effect: "Allow"


python_requirements:
  - cfn-response
