---
project: apigateway
default-region: eu-west-1
code-bucket: gordon-apigateway-0do1mc7
apps:
  - gordon.contrib.lambdas
  - helloworld

apigateway:
    helloapi:
        description: My first API
        resources:
            /:
                methods: [GET, POST]
                integration:
                    lambda: helloworld.hellopy

            /hi-from-js:
                methods: GET
                integration:
                    lambda: helloworld.hellojs

            /404:
                methods: GET
                integration:
                    lambda: helloworld.hellopy
                    responses:
                        - pattern: ""
                          code: "404"
                responses:
                    - code: "404"

            /shop/{item}:
                methods: GET
                integration:
                    lambda: helloworld.hellopy

            /http:
                methods: GET
                integration:
                    type: HTTP
                    uri: http://www.terra.es

            /mock:
                methods: GET
                integration:
                    type: MOCK

            /complex/implementation:
                methods:
                    GET:
                        integration:
                            lambda: helloworld.hellopy
                    POST:
                        integration:
                            lambda: helloworld.hellojs
