---
project: apigatewayexample8
default-region: eu-west-1
apps:
  - gordon.contrib.lambdas
  - gordon.contrib.apigateway
  - himachine

api:
  my-api:
    description: My first API
    # domains:
    #   mydomain.com:
    #     cert_name:
    #     cert_body:
    #     cert_private_key:
    #     cert_chain:
    # models:
    #   model_a:
    #     content-type: application/json
    #     description: xxx
    #     schema: |
    #       {
    #         "$schema" : "http://json-schema.org/draft-04/schema#",
    #         "title" : "Error Schema",
    #         "type" : "object",
    #         "properties" : {
    #           "message" : { "type" : "string" }
    #         }
    #       }

#urls-default-api: my-api

urls:
  /hello/:
    api: my-api
    lambda: exampleapp.hellopy
    methods:
      - GET
      - POST

  # /hello/{parameter}/:
  #   api: default
  #   proxy: http://...
  #   methods:
  #     - GET:
  #       lambda: simple.functions.hello_world_get
  #     - POST:
  #       lambda: simple.functions.hello_world_post



      #methods:
      #  GET:

      #stage:
      #security:
