lambdas:

  bucket_notification_configuration:
    code: bucket_notification_configuration
    handler: bucket_notification_configuration.handler
    runtime: python
    description: Manages Bucket Notification Configurations
    timeout: 300
    policies:
      read_kinesis:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "s3:PutBucketNotification"
              - "s3:GetBucketNotification"
            Resource: "arn:aws:s3:::*"
            Effect: "Allow"
