lambdas:
  gordon_contrib_utils_sleep:
    code: sleep.py
    description: Simple Lambda which sleeps for some seconds. The cloud they said! 128Mb of ram sleeping - What a time be alive...
    timeout: 300
    python_requirements:
      - cfn-response
