---
project: cron5
default-region: eu-west-1
code-bucket: gordon-cron5-0do1mc8
apps:
  - gordon.contrib.lambdas
  - helloworld

cron:
  every_night:
    expression: rate(1 minute)
    lambda: helloworld.hellopy
