lambdas:
  dynamoconsumer:
    code: dynamoconsumer.py
    #update_current_alias: false
    policies:
      read_dynamo:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "dynamodb:DescribeStream"
              - "dynamodb:ListStreams"
              - "dynamodb:GetShardIterator"
              - "dynamodb:GetRecords"
            Resource: "arn:aws:dynamodb:*:*:*"
            Effect: "Allow"
