lambdas:
  helloworld:
    code: helloworld
    runtime: java
    handler: helloworld.Hello::handler
    #description: Simple functions in python which says hello
    #handler: handler
    #role:
    #memory:
