---
project: dynamodbexample2
default-region: eu-west-1
apps:
  - gordon.contrib.helpers
  - gordon.contrib.lambdas
  - exampleapp

dynamodb:
  example_dynamo_integration:
    lambda: exampleapp.dynamoconsumer
    stream: ref://DynamoIntegrationArn
    batch_size: 1
    starting_position: LATEST
